name: Publish my site

on:
  push:
    branches:
      - main
    paths:
      - mysite/**    # Workflow run only when mysite folder updated

jobs:
  publish-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # checkout action - SHA version




      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mysite/dist   # Adjusted to match build output directory