name: Run Python test

on: 
  push:
    branches:
      - main
    paths:
      - ./hello_world/app.py    # Workflow run only when app.py updated

jobs:   # There may be one or many jobs, One job = one runner
  run-python-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependancies
        run: | 
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: pytest