name: Run Python test

on: 
  push:
    branches:
      - main
    paths:
      - app.py

jobs:
  run-python-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependancies
        run: | 
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: pytest